# Generated by Django 5.2.6 on 2025-11-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
