# Generated by Django 5.2.6 on 2025-11-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='referral_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='referral_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='service',
            name='referral_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
