# Generated by Django 5.2.6 on 2025-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_course_category_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='whatsapp_message',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='course',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='E.g. 919999999999 without +', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp_message',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='E.g. 919999999999 without +', max_length=20),
        ),
    ]
