# Generated by Django 5.2.6 on 2025-12-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_course_whatsapp_message_course_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('course', 'Course')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'course'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'name', 'type')},
        ),
    ]
