"""
Django settings for zinda_store project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ # type: ignore

# Ensure PyMySQL is used as MySQLdb for Django's MySQL backend
try:
    import pymysql  # type: ignore
    pymysql.install_as_MySQLdb()
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variables
env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=(str, 'django-insecure-placeholder'),
    ALLOWED_HOSTS=(list, []),
    DB_NAME=(str, 'zinda_store_db'),
    DB_USER=(str, 'root'),
    DB_PASSWORD=(str, 'pass123'),
    DB_HOST=(str, '127.0.0.1'),
    DB_PORT=(int, 33306),
    RAZORPAY_KEY_ID=(str, ''),
    RAZORPAY_KEY_SECRET=(str, ''),
    RAZORPAY_WEBHOOK_SECRET=(str, ''),
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    # Third-party admin theme
    'unfold',

    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    
     'corsheaders',

    # Local apps
    'core',
    'catalog',
    'inventory',
    'cart',
    'orders',
    'payments',
    'shipping',
    'promotions',
    'reviews',
    'support',
    'cms',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zinda_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zinda_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
ALLOWED_HOSTS = ['*']

# Currency configuration
DEFAULT_CURRENCY = 'INR'

# Razorpay configuration
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET')
RAZORPAY_WEBHOOK_SECRET = env('RAZORPAY_WEBHOOK_SECRET')

# Django REST Framework minimal settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
}
JORA_BASE_URL = 'https://server2.jobzinda.com/api/v1'
# Unfold basic configuration (optional, can be extended later)
UNFOLD = {
    'SITE_TITLE': 'Zinda Store Admin',
    'SITE_HEADER': 'Zinda Store',
    "SITE_LOGO": "/static/branding/logo.png",
    # Load custom CSS to tweak input borders/appearance
    "STYLES": [
        "/static/branding/admin-overrides.css",
    ],
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "Dashboard",
                "items": [
                    {
                        "title": "Overview",
                        "icon": "space_dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Authentication & Authorization",
                "collapsible": True,
                "items": [
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": "/admin/auth/group/",
                    },
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": "/admin/auth/user/",
                    },
                ],
            },
            {
                "title": "Catalog",
                "collapsible": True,
                "items": [
                    {
                        "title": "Brands",
                        "icon": "store",
                        "link": "/admin/catalog/brand/",
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": "/admin/catalog/category/",
                    },
                    {
                        "title": "Product images",
                        "icon": "photo_library",
                        "link": "/admin/catalog/productimage/",
                    },
                    {
                        "title": "Product variants",
                        "icon": "widgets",
                        "link": "/admin/catalog/productvariant/",
                    },
                    {
                        "title": "Products",
                        "icon": "inventory_2",
                        "link": "/admin/catalog/product/",
                    },
                ],
            },
            {
                "title": "CMS",
                "collapsible": True,
                "items": [
                    {
                        "title": "Banners",
                        "icon": "collections_bookmark",
                        "link": "/admin/cms/banner/",
                    },
                    {
                        "title": "Pages",
                        "icon": "description",
                        "link": "/admin/cms/page/",
                    },
                ],
            },
            {
                "title": "Inventory",
                "collapsible": True,
                "items": [
                    {
                        "title": "Warehouses",
                        "icon": "warehouse",
                        "link": "/admin/inventory/warehouse/",
                    },
                    {
                        "title": "Inventory items",
                        "icon": "inventory",
                        "link": "/admin/inventory/inventoryitem/",
                    },
                    {
                        "title": "Stock movements",
                        "icon": "sync_alt",
                        "link": "/admin/inventory/stockmovement/",
                    },
                ],
            },
            {
                "title": "Cart",
                "collapsible": True,
                "items": [
                    {
                        "title": "Carts",
                        "icon": "shopping_cart",
                        "link": "/admin/cart/cart/",
                    },
                ],
            },
            {
                "title": "Orders",
                "collapsible": True,
                "items": [
                    {
                        "title": "Orders",
                        "icon": "receipt_long",
                        "link": "/admin/orders/order/",
                    },
                    {
                        "title": "Invoices",
                        "icon": "request_quote",
                        "link": "/admin/orders/invoice/",
                    },
                ],
            },
            {
                "title": "Payments",
                "collapsible": True,
                "items": [
                    {
                        "title": "Payment intents",
                        "icon": "payments",
                        "link": "/admin/payments/paymentintent/",
                    },
                    {
                        "title": "Refunds",
                        "icon": "undo",
                        "link": "/admin/payments/refund/",
                    },
                ],
            },
            {
                "title": "Shipping",
                "collapsible": True,
                "items": [
                    {
                        "title": "Shipping methods",
                        "icon": "local_shipping",
                        "link": "/admin/shipping/shippingmethod/",
                    },
                    {
                        "title": "Shipments",
                        "icon": "move_up",
                        "link": "/admin/shipping/shipment/",
                    },
                    {
                        "title": "Shipment items",
                        "icon": "inventory_2",
                        "link": "/admin/shipping/shipmentitem/",
                    },
                ],
            },
            {
                "title": "Promotions",
                "collapsible": True,
                "items": [
                    {
                        "title": "Coupons",
                        "icon": "loyalty",
                        "link": "/admin/promotions/coupon/",
                    },
                ],
            },
            {
                "title": "Reviews",
                "collapsible": True,
                "items": [
                    {
                        "title": "Reviews",
                        "icon": "reviews",
                        "link": "/admin/reviews/review/",
                    },
                ],
            },
            {
                "title": "Support",
                "collapsible": True,
                "items": [
                    {
                        "title": "Return requests",
                        "icon": "support_agent",
                        "link": "/admin/support/returnrequest/",
                    },
                ],
            },
        ],
    },

    "LOGIN": {
        # Shown on the login screen (logo)
        "LOGO": "/static/branding/logo.png",
        # Optional illustration/image on login page
        # "IMAGE": "/static/branding/login-illustration.svg",
        # Optional: title/intro text
        # "TITLE": "Welcome back",
        # "SUBTITLE": "Sign in to Zinda Store Admin",
    },
}
