# Generated by Django 5.2.15 on 2026-08-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_commission_amount_order_promoter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promoter_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promoter_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='referral_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
